/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Clases.ConexionBD;
import Clases.cModificar;
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author nico_
 */
public class Principal extends javax.swing.JFrame {
    private Timer timer;
    String Cnombre="Sin nombre";
    cModificar cmo = new cModificar();
    ArrayList<String> datosob = new ArrayList<>();
    private static Connection con;
    private static final String driver="com.mysql.jdbc.Driver";
    private static final String user="root";
    private static final String pass="";
    private static final String url="jdbc:mysql://localhost:3306/wurlitzerdb";
    //Conectarse a mi bd de mysql
    public void conector() {
        // Reseteamos a null la conexion a la bd
        con=null;
        try{
            Class.forName(driver);
            // Nos conectamos a la bd
            con= (Connection) DriverManager.getConnection(url, user, pass);
            // Si la conexion fue exitosa mostramos un mensaje de conexion exitosa
            if (con!=null){
                teEstado.setForeground(Color.GREEN);
                teEstado.setText("Conexión establecida");
            }
        }
        // Si la conexion NO fue exitosa mostramos un mensaje de error
        catch (ClassNotFoundException | SQLException e){
            teEstado.setForeground(Color.RED);
            teEstado.setText("Error de conexión" + e);
        }
    }
    ConexionBD cone = new ConexionBD();
    Connection cn = (Connection) cone.conexion();
    
    
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        botones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BoAgregar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        BoModificar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        BoEliminar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        Listar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        BoSolicitar = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        BoInicio = new javax.swing.JButton();
        pestañas = new javax.swing.JTabbedPane();
        jInicio = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        titReproduccion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BoConectar = new javax.swing.JButton();
        teEstado = new javax.swing.JLabel();
        cerrar2 = new javax.swing.JButton();
        jAgregar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        textTitulo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textAutor = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textDisco = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textAnio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textDuracion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        textEstilo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        aGuardar = new javax.swing.JButton();
        aLimpiar = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        cerrar = new javax.swing.JButton();
        jModificar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        textTitulo1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        textAutor1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        textDisco1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        textAnio1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        textDuracion1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        textEstilo1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        mModificar = new javax.swing.JButton();
        buscarcan = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cerrar1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        textId1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jEliminar = new javax.swing.JPanel();
        jListar = new javax.swing.JPanel();
        jSolicitar = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        setSize(new java.awt.Dimension(570, 370));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botones.setBackground(new java.awt.Color(3, 4, 94));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DuocWurlitzer");

        BoAgregar.setBackground(new java.awt.Color(3, 4, 94));
        BoAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BoAgregar.setText("Agregar");
        BoAgregar.setBorder(null);
        BoAgregar.setBorderPainted(false);
        BoAgregar.setFocusPainted(false);
        BoAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoAgregarActionPerformed(evt);
            }
        });

        BoModificar.setBackground(new java.awt.Color(3, 4, 94));
        BoModificar.setForeground(new java.awt.Color(255, 255, 255));
        BoModificar.setText("Modificar");
        BoModificar.setBorderPainted(false);
        BoModificar.setFocusPainted(false);
        BoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoModificarActionPerformed(evt);
            }
        });

        BoEliminar.setBackground(new java.awt.Color(3, 4, 94));
        BoEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BoEliminar.setText("Eliminar");
        BoEliminar.setBorderPainted(false);
        BoEliminar.setFocusPainted(false);
        BoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoEliminarActionPerformed(evt);
            }
        });

        Listar.setBackground(new java.awt.Color(3, 4, 94));
        Listar.setForeground(new java.awt.Color(255, 255, 255));
        Listar.setText("Listar");
        Listar.setBorderPainted(false);
        Listar.setFocusPainted(false);
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });

        BoSolicitar.setBackground(new java.awt.Color(3, 4, 94));
        BoSolicitar.setForeground(new java.awt.Color(255, 255, 255));
        BoSolicitar.setText("Solicitar");
        BoSolicitar.setBorderPainted(false);
        BoSolicitar.setFocusPainted(false);
        BoSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoSolicitarActionPerformed(evt);
            }
        });

        BoInicio.setBackground(new java.awt.Color(3, 4, 94));
        BoInicio.setForeground(new java.awt.Color(255, 255, 255));
        BoInicio.setText("Inicio");
        BoInicio.setBorderPainted(false);
        BoInicio.setFocusPainted(false);
        BoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botonesLayout = new javax.swing.GroupLayout(botones);
        botones.setLayout(botonesLayout);
        botonesLayout.setHorizontalGroup(
            botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addComponent(BoAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(BoModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator3)
            .addComponent(BoEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator4)
            .addComponent(Listar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator5)
            .addComponent(BoSolicitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator6)
            .addComponent(BoInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        botonesLayout.setVerticalGroup(
            botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BoAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BoModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BoEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Listar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BoSolicitar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BoInicio)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel1.add(botones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 400));

        pestañas.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jInicio.setBackground(new java.awt.Color(144, 224, 239));
        jInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBackground(new java.awt.Color(0, 180, 216));

        jLabel2.setText("Titulo");

        titReproduccion.setText("Sin nombre");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(titReproduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(titReproduccion)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabel4.setText("Autor");

        jLabel5.setText("Sin nombre");

        jLabel6.setText("Disco");

        jLabel7.setText("Sin nombre");

        BoConectar.setText("Contectar");
        BoConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoConectarActionPerformed(evt);
            }
        });

        teEstado.setText("Estado");

        cerrar2.setBackground(new java.awt.Color(3, 4, 94));
        cerrar2.setForeground(new java.awt.Color(255, 255, 255));
        cerrar2.setText("X");
        cerrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInicioLayout = new javax.swing.GroupLayout(jInicio);
        jInicio.setLayout(jInicioLayout);
        jInicioLayout.setHorizontalGroup(
            jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInicioLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addGroup(jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInicioLayout.createSequentialGroup()
                            .addComponent(cerrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInicioLayout.createSequentialGroup()
                            .addComponent(BoConectar)
                            .addGap(18, 18, 18)
                            .addComponent(teEstado)
                            .addGap(66, 66, 66))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInicioLayout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(111, 111, 111)))
                    .addGroup(jInicioLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)))))
        );
        jInicioLayout.setVerticalGroup(
            jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInicioLayout.createSequentialGroup()
                .addComponent(cerrar2)
                .addGap(4, 4, 4)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BoConectar)
                    .addComponent(teEstado))
                .addContainerGap())
        );

        pestañas.addTab("tab6", jInicio);

        jAgregar.setBackground(new java.awt.Color(144, 224, 239));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Titulo");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        textTitulo.setForeground(new java.awt.Color(102, 102, 102));
        textTitulo.setText("Ingrese el título de la canción");
        textTitulo.setBorder(null);
        textTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textTituloMousePressed(evt);
            }
        });
        textTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTituloActionPerformed(evt);
            }
        });
        jPanel2.add(textTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 350, -1));

        jLabel9.setText("Autor");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        textAutor.setForeground(new java.awt.Color(102, 102, 102));
        textAutor.setText("¿Quién es el autor?");
        textAutor.setBorder(null);
        textAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textAutorMousePressed(evt);
            }
        });
        textAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAutorActionPerformed(evt);
            }
        });
        jPanel2.add(textAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 350, -1));

        jLabel10.setText("Disco");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        textDisco.setForeground(new java.awt.Color(102, 102, 102));
        textDisco.setText("Nombre del disco");
        textDisco.setBorder(null);
        textDisco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textDiscoMousePressed(evt);
            }
        });
        jPanel2.add(textDisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 350, -1));

        jLabel11.setText("Año");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        textAnio.setForeground(new java.awt.Color(102, 102, 102));
        textAnio.setText("Año de lanzamiento");
        textAnio.setBorder(null);
        textAnio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textAnioMousePressed(evt);
            }
        });
        textAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAnioActionPerformed(evt);
            }
        });
        jPanel2.add(textAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 406, -1));

        jLabel12.setText("Duración");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        textDuracion.setForeground(new java.awt.Color(102, 102, 102));
        textDuracion.setText("Tiempo de duración de la canción indicado en segundos");
        textDuracion.setBorder(null);
        textDuracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textDuracionMousePressed(evt);
            }
        });
        jPanel2.add(textDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 406, -1));

        jLabel13.setText("Estilo");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 10));

        textEstilo.setForeground(new java.awt.Color(102, 102, 102));
        textEstilo.setText("Ej: Rock, Pop, Reggaeton, Rap, etc...");
        textEstilo.setBorder(null);
        textEstilo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textEstiloMousePressed(evt);
            }
        });
        textEstilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEstiloActionPerformed(evt);
            }
        });
        jPanel2.add(textEstilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 190, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Agregar");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 25, -1, -1));

        aGuardar.setBackground(new java.awt.Color(0, 180, 216));
        aGuardar.setForeground(new java.awt.Color(255, 255, 255));
        aGuardar.setText("Guardar");
        aGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(aGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 346, -1, -1));

        aLimpiar.setBackground(new java.awt.Color(0, 180, 216));
        aLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        aLimpiar.setText("Limpiar");
        aLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(aLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 346, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 350, -1));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 350, -1));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 350, -1));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 350, -1));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 350, -1));

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 175, -1));

        cerrar.setBackground(new java.awt.Color(3, 4, 94));
        cerrar.setForeground(new java.awt.Color(255, 255, 255));
        cerrar.setText("X");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jAgregarLayout = new javax.swing.GroupLayout(jAgregar);
        jAgregar.setLayout(jAgregarLayout);
        jAgregarLayout.setHorizontalGroup(
            jAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jAgregarLayout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jAgregarLayout.setVerticalGroup(
            jAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jAgregarLayout.createSequentialGroup()
                        .addComponent(cerrar)
                        .addGap(0, 366, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pestañas.addTab("tab1", jAgregar);

        jModificar.setBackground(new java.awt.Color(3, 4, 94));

        jPanel4.setBackground(new java.awt.Color(0, 119, 182));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Titulo");

        textTitulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTitulo1ActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Autor");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Disco");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Año");

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Duración");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Estilo");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Modificar");

        mModificar.setBackground(new java.awt.Color(0, 119, 182));
        mModificar.setForeground(new java.awt.Color(255, 255, 255));
        mModificar.setText("Modificar");

        buscarcan.setText("Buscar canción...");

        jButton1.setBackground(new java.awt.Color(0, 119, 182));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Limpiar");

        cerrar1.setBackground(new java.awt.Color(3, 4, 94));
        cerrar1.setForeground(new java.awt.Color(255, 255, 255));
        cerrar1.setText("X");
        cerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrar1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 119, 182));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imbuscar.png"))); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        textId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textId1ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Id");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(textDuracion1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mModificar)
                        .addGap(34, 34, 34))
                    .addComponent(textTitulo1)
                    .addComponent(textDisco1)
                    .addComponent(textAutor1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(cerrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(textId1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel16)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(100, 100, 100)
                                .addComponent(buscarcan, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textAnio1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addGap(193, 193, 193)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textEstilo1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)))
                            .addComponent(jLabel17)
                            .addComponent(jLabel15))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cerrar1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21)))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(buscarcan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textAutor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textDisco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEstilo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAnio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mModificar)
                    .addComponent(jButton1)
                    .addComponent(textDuracion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jModificarLayout = new javax.swing.GroupLayout(jModificar);
        jModificar.setLayout(jModificarLayout);
        jModificarLayout.setHorizontalGroup(
            jModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jModificarLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jModificarLayout.setVerticalGroup(
            jModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pestañas.addTab("tab2", jModificar);

        javax.swing.GroupLayout jEliminarLayout = new javax.swing.GroupLayout(jEliminar);
        jEliminar.setLayout(jEliminarLayout);
        jEliminarLayout.setHorizontalGroup(
            jEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );
        jEliminarLayout.setVerticalGroup(
            jEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        pestañas.addTab("tab3", jEliminar);

        javax.swing.GroupLayout jListarLayout = new javax.swing.GroupLayout(jListar);
        jListar.setLayout(jListarLayout);
        jListarLayout.setHorizontalGroup(
            jListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );
        jListarLayout.setVerticalGroup(
            jListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        pestañas.addTab("tab4", jListar);

        javax.swing.GroupLayout jSolicitarLayout = new javax.swing.GroupLayout(jSolicitar);
        jSolicitar.setLayout(jSolicitarLayout);
        jSolicitarLayout.setHorizontalGroup(
            jSolicitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );
        jSolicitarLayout.setVerticalGroup(
            jSolicitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        pestañas.addTab("tab5", jSolicitar);

        jPanel1.add(pestañas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoAgregarActionPerformed
        // TODO add your handling code here:
        pestañas.setSelectedIndex(1);
    }//GEN-LAST:event_BoAgregarActionPerformed

    private void BoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoModificarActionPerformed
        // TODO add your handling code here:
        pestañas.setSelectedIndex(2);
    }//GEN-LAST:event_BoModificarActionPerformed

    private void BoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoInicioActionPerformed
        // TODO add your handling code here:
        pestañas.setSelectedIndex(0);
    }//GEN-LAST:event_BoInicioActionPerformed

    private void BoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoEliminarActionPerformed
        // TODO add your handling code here:
        pestañas.setSelectedIndex(3);
    }//GEN-LAST:event_BoEliminarActionPerformed

    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
        // TODO add your handling code here:
        pestañas.setSelectedIndex(4);
    }//GEN-LAST:event_ListarActionPerformed

    private void BoSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoSolicitarActionPerformed
        // TODO add your handling code here:
        pestañas.setSelectedIndex(5);
    }//GEN-LAST:event_BoSolicitarActionPerformed

    private void BoConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoConectarActionPerformed
        // TODO add your handling code here:
        conector();
    }//GEN-LAST:event_BoConectarActionPerformed

    private void textTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTituloActionPerformed

    private void textTitulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTitulo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTitulo1ActionPerformed

    private void textEstiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEstiloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEstiloActionPerformed

    private void textAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAnioActionPerformed
//Guardar cancion en la base de datos
    private void aGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aGuardarActionPerformed
        boolean flag1= true;
        if(textTitulo.getText().isEmpty()||textTitulo.getText().equals("Ingrese el título de la canción")){
        textTitulo.setForeground(Color.red);
        textTitulo.setText("*Campo obligatorio");
        flag1= false;
        }
        if(textAutor.getText().isEmpty()||textAutor.getText().equals("¿Quién es el autor?")){
        textAutor.setForeground(Color.red);
        textAutor.setText("*Campo obligatorio");
        flag1= false;
        }
        if(textDisco.getText().isEmpty()||textDisco.getText().equals("Nombre del disco")){
        textDisco.setForeground(Color.red);
        textDisco.setText("*Campo obligatorio");
        flag1= false;
        }
        
        
        
        if(textDuracion.getText().isEmpty()||textDuracion.getText().equals("Ingrese el título de la canción")){
        textDuracion.setForeground(Color.red);
        textDuracion.setText("*Campo obligatorio");
        flag1= false;
        }
            double duracions = Double.parseDouble(textDuracion.getText());
            double duracionm = duracions/60;
        
        if(textAnio.getText().isEmpty()||textAnio.getText().equals("¿Quién es el autor?")){
        textAnio.setForeground(Color.red);
        textAnio.setText("*Campo obligatorio");
        flag1= false;
        }
        if(textEstilo.getText().isEmpty()||textEstilo.getText().equals("Nombre del disco")){
        textEstilo.setForeground(Color.red);
        textEstilo.setText("*Campo obligatorio");
        flag1= false;
        }
        if(flag1){
            try {
                PreparedStatement pps =cn.prepareStatement("INSERT INTO canciones(titulo,autor,disco,anio,duracions,duracionm,estilo) VALUES(?, ?, ?, ?, ?, ?, ?)");
                pps.setString(1, textTitulo.getText());
                pps.setString(2, textAutor.getText());
                pps.setString(3, textDisco.getText());
                pps.setString(4, textAnio.getText());
                pps.setString(5, textDuracion.getText());
                pps.setString(6, String.valueOf(duracionm));
                pps.setString(7, textEstilo.getText());
                pps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Datos Agregados");
            } catch (SQLException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_aGuardarActionPerformed
//Cerrar
    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cerrarActionPerformed

    private void cerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrar1ActionPerformed

    private void cerrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrar2ActionPerformed

    private void textTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textTituloMousePressed
        if(textTitulo.getText().equals("Ingrese el título de la canción")||textTitulo.getText().equals("*Campo obligario")){
            textTitulo.setText("");
            textTitulo.setForeground(Color.black);
        
        }
        if(textAutor.getText().isEmpty()){
            textAutor.setText("¿Quién es el autor?");
            textAutor.setForeground(new Color(102, 102, 102)); 
        }
        if(textAnio.getText().isEmpty()){
            textAnio.setText("Año de lanzamiento");
            textAnio.setForeground(new Color(102, 102, 102)); 
        }
        if(textDisco.getText().isEmpty()){
            textDisco.setText("Nombre del disco");
            textDisco.setForeground(new Color(102, 102, 102)); 
        }
        if(textDuracion.getText().isEmpty()){
            textDuracion.setText("Tiempo de duración de la canción indicado en segundos");
            textDuracion.setForeground(new Color(102, 102, 102)); 
        }
        if(textEstilo.getText().isEmpty()){
            textEstilo.setText("Ej: Rock, Pop, Reggaeton, Rap, etc...");
            textEstilo.setForeground(new Color(102, 102, 102)); 
        }
        
        
    }//GEN-LAST:event_textTituloMousePressed

    private void textAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAutorActionPerformed

    private void textAutorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textAutorMousePressed
        if(textAutor.getText().equals("¿Quién es el autor?")){
            textAutor.setText("");
            textAutor.setForeground(Color.black);
        }
        if(textTitulo.getText().isEmpty()){
            textTitulo.setText("Ingrese el título de la canción");
            textTitulo.setForeground(new Color(102, 102, 102)); 
        }
        if(textAnio.getText().isEmpty()){
            textAnio.setText("Año de lanzamiento");
            textAnio.setForeground(new Color(102, 102, 102)); 
        }
        if(textDisco.getText().isEmpty()){
            textDisco.setText("Nombre del disco");
            textDisco.setForeground(new Color(102, 102, 102)); 
        }
        if(textDuracion.getText().isEmpty()){
            textDuracion.setText("Tiempo de duración de la canción indicado en segundos");
            textDuracion.setForeground(new Color(102, 102, 102)); 
        }
        if(textEstilo.getText().isEmpty()){
            textEstilo.setText("Ej: Rock, Pop, Reggaeton, Rap, etc...");
            textEstilo.setForeground(new Color(102, 102, 102)); 
        }
    }//GEN-LAST:event_textAutorMousePressed

    private void textDiscoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textDiscoMousePressed
        // TODO add your handling code here:
        if(textDisco.getText().equals("Nombre del disco")){
            textDisco.setText("");
            textDisco.setForeground(Color.black);
        }
        if(textTitulo.getText().isEmpty()){
            textTitulo.setText("Ingrese el título de la canción");
            textTitulo.setForeground(new Color(102, 102, 102)); 
        }
        if(textAnio.getText().isEmpty()){
            textAnio.setText("Año de lanzamiento");
            textAnio.setForeground(new Color(102, 102, 102)); 
        }
        if(textAutor.getText().isEmpty()){
            textAutor.setText("¿Quién es el autor?");
            textAutor.setForeground(new Color(102, 102, 102)); 
        }
        if(textDuracion.getText().isEmpty()){
            textDuracion.setText("Tiempo de duración de la canción indicado en segundos");
            textDuracion.setForeground(new Color(102, 102, 102)); 
        }
        if(textEstilo.getText().isEmpty()){
            textEstilo.setText("Ej: Rock, Pop, Reggaeton, Rap, etc...");
            textEstilo.setForeground(new Color(102, 102, 102)); 
        }
    }//GEN-LAST:event_textDiscoMousePressed

    private void textAnioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textAnioMousePressed
        // TODO add your handling code here:
        if(textAnio.getText().equals("Año de lanzamiento")){
            textAnio.setText("");
            textAnio.setForeground(Color.black);
        }
        if(textTitulo.getText().isEmpty()){
            textTitulo.setText("Ingrese el título de la canción");
            textTitulo.setForeground(new Color(102, 102, 102)); 
        }
        if(textDisco.getText().isEmpty()){
            textDisco.setText("Nombre del disco");
            textDisco.setForeground(new Color(102, 102, 102)); 
        }
        if(textAutor.getText().isEmpty()){
            textAutor.setText("¿Quién es el autor?");
            textAutor.setForeground(new Color(102, 102, 102)); 
        }
        if(textDuracion.getText().isEmpty()){
            textDuracion.setText("Tiempo de duración de la canción indicado en segundos");
            textDuracion.setForeground(new Color(102, 102, 102)); 
        }
        if(textEstilo.getText().isEmpty()){
            textEstilo.setText("Ej: Rock, Pop, Reggaeton, Rap, etc...");
            textEstilo.setForeground(new Color(102, 102, 102)); 
        }
        
    }//GEN-LAST:event_textAnioMousePressed

    private void textDuracionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textDuracionMousePressed
        // TODO add your handling code here:
        if(textDuracion.getText().equals("Tiempo de duración de la canción indicado en segundos")){
            textDuracion.setText("");
            textDuracion.setForeground(Color.black);
        }
        if(textTitulo.getText().isEmpty()){
            textTitulo.setText("Ingrese el título de la canción");
            textTitulo.setForeground(new Color(102, 102, 102)); 
        }
        if(textDisco.getText().isEmpty()){
            textDisco.setText("Nombre del disco");
            textDisco.setForeground(new Color(102, 102, 102)); 
        }
        if(textAutor.getText().isEmpty()){
            textAutor.setText("¿Quién es el autor?");
            textAutor.setForeground(new Color(102, 102, 102)); 
        }
        if(textAnio.getText().isEmpty()){
            textAnio.setText("Año de lanzamiento");
            textAnio.setForeground(new Color(102, 102, 102)); 
        }
        if(textEstilo.getText().isEmpty()){
            textEstilo.setText("Ej: Rock, Pop, Reggaeton, Rap, etc...");
            textEstilo.setForeground(new Color(102, 102, 102)); 
        }
    }//GEN-LAST:event_textDuracionMousePressed

    private void textEstiloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textEstiloMousePressed
        // TODO add your handling code here:
        if(textEstilo.getText().equals("Ej: Rock, Pop, Reggaeton, Rap, etc...")){
            textEstilo.setText("");
            textEstilo.setForeground(Color.black);
        }
        if(textTitulo.getText().isEmpty()){
            textTitulo.setText("Ingrese el título de la canción");
            textTitulo.setForeground(new Color(102, 102, 102)); 
        }
        if(textDisco.getText().isEmpty()){
            textDisco.setText("Nombre del disco");
            textDisco.setForeground(new Color(102, 102, 102)); 
        }
        if(textAutor.getText().isEmpty()){
            textAutor.setText("¿Quién es el autor?");
            textAutor.setForeground(new Color(102, 102, 102)); 
        }
        if(textAnio.getText().isEmpty()){
            textAnio.setText("Año de lanzamiento");
            textAnio.setForeground(new Color(102, 102, 102)); 
        }
        if(textDuracion.getText().isEmpty()){
            textDuracion.setText("Tiempo de duración de la canción indicado en segundos");
            textDuracion.setForeground(new Color(102, 102, 102)); 
        }
    }//GEN-LAST:event_textEstiloMousePressed
//Limpiar las casillas de agregar canciones
    private void aLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aLimpiarActionPerformed
        textTitulo.setText("Ingrese el título de la canción");
        textTitulo.setForeground(new Color(102, 102, 102)); 
        textDisco.setText("Nombre del disco");
        textDisco.setForeground(new Color(102, 102, 102)); 
        textAutor.setText("¿Quién es el autor?");
        textAutor.setForeground(new Color(102, 102, 102)); 
        textAnio.setText("Año de lanzamiento");
        textAnio.setForeground(new Color(102, 102, 102)); 
        textDuracion.setText("Tiempo de duración de la canción indicado en segundos");
        textDuracion.setForeground(new Color(102, 102, 102)); 
        textEstilo.setText("Ej: Rock, Pop, Reggaeton, Rap, etc...");
        textEstilo.setForeground(new Color(102, 102, 102)); 
    }//GEN-LAST:event_aLimpiarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(buscarcan.getText().equals("Buscar canción...") || buscarcan.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese el nombre de una canción...", "Error", JOptionPane.WARNING_MESSAGE);
        }else if(cmo.consultarUsuarioBuscar(buscarcan.getText()).isEmpty()){
            JOptionPane.showMessageDialog(null, "No se encontró la cancion", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            datosob = cmo.consultarUsuarioBuscar(buscarcan.getText());
            System.out.println(datosob);
            textId1.setText(datosob.get(0));
            textTitulo1.setText(datosob.get(1));
            textAutor1.setText(datosob.get(2));
            textDisco1.setText(datosob.get(3));
            textAnio1.setText(datosob.get(4));
            textDuracion1.setText(datosob.get(5));
            textEstilo1.setText(datosob.get(6));
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void textId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textId1ActionPerformed
    //animacion del titulo de inicio


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoAgregar;
    private javax.swing.JButton BoConectar;
    private javax.swing.JButton BoEliminar;
    private javax.swing.JButton BoInicio;
    private javax.swing.JButton BoModificar;
    private javax.swing.JButton BoSolicitar;
    private javax.swing.JButton Listar;
    private javax.swing.JButton aGuardar;
    private javax.swing.JButton aLimpiar;
    private javax.swing.JPanel botones;
    private javax.swing.JTextField buscarcan;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton cerrar1;
    private javax.swing.JButton cerrar2;
    private javax.swing.JPanel jAgregar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jEliminar;
    private javax.swing.JPanel jInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jListar;
    private javax.swing.JPanel jModificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel jSolicitar;
    private javax.swing.JButton mModificar;
    private javax.swing.JTabbedPane pestañas;
    private javax.swing.JLabel teEstado;
    private javax.swing.JTextField textAnio;
    private javax.swing.JTextField textAnio1;
    private javax.swing.JTextField textAutor;
    private javax.swing.JTextField textAutor1;
    private javax.swing.JTextField textDisco;
    private javax.swing.JTextField textDisco1;
    private javax.swing.JTextField textDuracion;
    private javax.swing.JTextField textDuracion1;
    private javax.swing.JTextField textEstilo;
    private javax.swing.JTextField textEstilo1;
    private javax.swing.JTextField textId1;
    private javax.swing.JTextField textTitulo;
    private javax.swing.JTextField textTitulo1;
    private javax.swing.JLabel titReproduccion;
    // End of variables declaration//GEN-END:variables
}
